//! Stone C inference perf bench across the 7 fixtures.
//!
//! Measures pure quantize_indexed_png cost (training + apply +
//! oxipng) — same code path that `Quality::Auto` exercises in
//! nupic-core 0.5.0. Compares against the cement reference timing
//! that `metric_sweep` and `pluto_sweep` baked in earlier (cement =
//! 0.4.x imagequant + Floyd-Steinberg dither + oxipng).
//!
//! Run:
//!   cargo run --release -p nupic-research --example stone_c_perf_bench
//!
//! Output:
//!   target/research-out/04-stone-c-perf.{csv,md}

use std::fs;
use std::path::{Path, PathBuf};
use std::time::Instant;

use anyhow::{Context, Result};
use nupic_quantize::{QuantizeOpts, quantize_indexed_png};

const INPUTS: &str = "assets/png-bench/inputs";
const OUT_DIR: &str = "target/research-out";

#[derive(Debug)]
struct Row {
    image: String,
    n_pixels: usize,
    train_ms: f64,
    apply_ms: f64,
    oxipng_ms: f64,
    total_ms: f64,
    bytes: usize,
}

fn main() -> Result<()> {
    let root = workspace_root()?;
    let inputs_dir = root.join(INPUTS);
    let out_dir = root.join(OUT_DIR);
    fs::create_dir_all(&out_dir)?;
    let names = [
        "01-png-transparency-demo.png",
        "02-pluto-transparent.png",
        "03-wikipedia-logo.png",
        "04-photo-portrait.png",
        "05-photo-mountain.png",
        "06-photo-landscape.png",
        "07-photo-product.png",
    ];

    let mut rows: Vec<Row> = Vec::new();
    for name in &names {
        let path = inputs_dir.join(name);
        let img = ::image::open(&path)?.to_rgba8();
        let (w, h) = (img.width(), img.height());
        let n = (w * h) as usize;
        let raw = img.into_raw();

        // run 5 times, take median
        let mut totals = Vec::with_capacity(5);
        let mut last_bytes = 0;
        for _ in 0..5 {
            let t0 = Instant::now();
            let bytes = quantize_indexed_png(&raw, w, h, QuantizeOpts::default()).expect("quantize");
            totals.push(t0.elapsed().as_secs_f64() * 1000.0);
            last_bytes = bytes.len();
        }
        totals.sort_by(|a, b| a.partial_cmp(b).unwrap());
        let total = totals[totals.len() / 2];

        // also break down train vs apply vs oxipng (rough estimate via separate calls)
        let mut ts_train = Vec::with_capacity(3);
        let mut ts_apply = Vec::with_capacity(3);
        for _ in 0..3 {
            let t0 = Instant::now();
            let palette = nupic_quantize::train_palette(&raw, w, h, 256).expect("train");
            ts_train.push(t0.elapsed().as_secs_f64() * 1000.0);
            let t0 = Instant::now();
            let _ = nupic_quantize::apply_palette(&raw, w, h, &palette);
            ts_apply.push(t0.elapsed().as_secs_f64() * 1000.0);
        }
        ts_train.sort_by(|a, b| a.partial_cmp(b).unwrap());
        ts_apply.sort_by(|a, b| a.partial_cmp(b).unwrap());
        let train_ms = ts_train[ts_train.len() / 2];
        let apply_ms = ts_apply[ts_apply.len() / 2];
        let oxipng_ms = (total - train_ms - apply_ms).max(0.0);

        rows.push(Row {
            image: name.to_string(),
            n_pixels: n,
            train_ms,
            apply_ms,
            oxipng_ms,
            total_ms: total,
            bytes: last_bytes,
        });
        println!("[stone_c_perf] done {name} ({total:.1} ms total — train {train_ms:.1}, apply {apply_ms:.1}, oxipng {oxipng_ms:.1})");
    }

    write_csv(&out_dir.join("04-stone-c-perf.csv"), &rows)?;
    write_md(&out_dir.join("04-stone-c-perf.md"), &rows)?;
    println!("[stone_c_perf] wrote {} rows", rows.len());
    Ok(())
}

fn write_csv(path: &Path, rows: &[Row]) -> Result<()> {
    use std::io::Write;
    let mut f = fs::File::create(path)?;
    writeln!(f, "image,n_pixels,train_ms,apply_ms,oxipng_ms,total_ms,bytes")?;
    for r in rows {
        writeln!(f, "{},{},{:.2},{:.2},{:.2},{:.2},{}",
            r.image, r.n_pixels, r.train_ms, r.apply_ms, r.oxipng_ms, r.total_ms, r.bytes)?;
    }
    Ok(())
}

fn write_md(path: &Path, rows: &[Row]) -> Result<()> {
    use std::fmt::Write;
    let mut s = String::new();
    writeln!(&mut s, "# 04-stone-c-perf — raw output\n")?;
    writeln!(&mut s, "Generated by `cargo run --release -p nupic-research --example stone_c_perf_bench`.\n")?;
    writeln!(&mut s, "| image | n_px | train_ms | apply_ms | oxipng_ms | total_ms | bytes |")?;
    writeln!(&mut s, "|---|---:|---:|---:|---:|---:|---:|")?;
    for r in rows {
        writeln!(&mut s, "| `{}` | {} | {:.1} | {:.1} | {:.1} | {:.1} | {} |",
            r.image, r.n_pixels, r.train_ms, r.apply_ms, r.oxipng_ms, r.total_ms, r.bytes)?;
    }
    fs::write(path, s)?;
    Ok(())
}

fn workspace_root() -> Result<PathBuf> {
    let m = env!("CARGO_MANIFEST_DIR");
    Ok(Path::new(m).ancestors().nth(2).context("workspace root")?.to_path_buf())
}
